name : Deploy CheckMyWarranty To AWS EC2

on: 
  push:
   branches:
    - main

jobs: 
  deploy:
    runs-on: ubuntu-latest

    steps: 
      - name: Checkout Code
        uses: action/checkout@v4

      - name: Deploy via SSH
        uses: appleboy/ssh-action@v1
        with: 
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            cd /home/ubuntu/CheckMyWarranty/backend
            git pull origin main
            docker compose -f docker-compose.prod.yml build
            docker compose -f docker-compose.prod.yml run --rm app npx prisma migrate deploy
            docker compose -f docker-compose.prod.yml up -d
            docker image prune -f